export const namespace = (action) => `RuntimeEngine/${action}`;

// actions name list
export const INITIALIZE_ENGINE = namespace('INITIALIZE_ENGINE');
export const DESTROY_ENGINE = namespace('DESTROY_ENGINE');
export const LOAD_HEADER_VALUES = namespace('LOAD_HEADER_VALUES');
export const LOAD_PAGE_DATA_CONFIG = namespace('LOAD_PAGE_DATA_CONFIG');
export const LOAD_CHILD_VALUES = namespace('LOAD_CHILD_VALUES');
export const UPDATE_HEADER_SECTIONS = namespace('UPDATE_HEADER_SECTIONS');
export const LOAD_META_DATA = namespace('LOAD_META_DATA');
export const LOAD_DEBUG_CONSOLE_META_DATA = namespace('LOAD_DEBUG_CONSOLE_META_DATA');
export const UPDATE_HEADER_FIELD = namespace('UPDATE_HEADER_FIELD');
export const UPDATE_HEADER_RECORD = namespace('UPDATE_HEADER_RECORD');
export const UPDATE_CHILD_RECORD = namespace('UPDATE_CHILD_RECORD');
export const UPDATE_RECORD_TYPES = namespace('UPDATE_RECORD_TYPES');
export const UPDATE_BLOCK_APPLICATION = namespace('UPDATE_BLOCK_APPLICATION');
export const UPDATE_UN_BLOCK_APPLICATION = namespace('UPDATE_UN_BLOCK_APPLICATION');
export const UPDATE_HEADER_CURRENCY = namespace('UPDATE_HEADER_CURRENCY');
export const ADD_TEMPORARY_CHILD_LINE = namespace('ADD_TEMPORARY_CHILD_LINE');
export const EDIT_TEMPORARY_CHILD_LINE = namespace('EDIT_TEMPORARY_CHILD_LINE');
export const COMMIT_TEMPORARY_CHILD_LINE = namespace('COMMIT_TEMPORARY_CHILD_LINE');
export const DISCARD_TEMPORARY_CHILD_LINE = namespace('DISCARD_TEMPORARY_CHILD_LINE');
export const UPDATE_TEMPORARY_CHILD_RECORD = namespace('UPDATE_TEMPORARY_CHILD_RECORD');
export const DELETE_CHILD_RECORDS = namespace('DELETE_CHILD_RECORDS');
export const CLONE_CHILD_LINE = namespace('CLONE_CHILD_LINE');
export const SELECTED_CHILD_LINES = namespace('SELECTED_CHILD_LINES');
export const UPDATE_VALIDATION_RESULTS = namespace('UPDATE_VALIDATION_RESULTS');
export const UPDATE_OBJECT_MAPPING = namespace('UPDATE_OBJECT_MAPPING');
export const UPDATE_OBJECT_MAPPINGS = namespace('UPDATE_OBJECT_MAPPINGS');
export const UPDATE_COMPLETE_OBJECT_DESCRIBES = namespace('UPDATE_COMPLETE_OBJECT_DESCRIBES');
export const UPDATE_EXPRESSION_DETAILS = namespace('UPDATE_EXPRESSION_DETAILS');
export const UPDATE_FORMATTED_EXPRESSION_FOR_OBJECT =
    namespace('UPDATE_FORMATTED_EXPRESSION_FOR_OBJECT');
export const UPDATE_FORMATTED_MAPPING_FOR_OBJECT =
    namespace('UPDATE_FORMATTED_MAPPING_FOR_OBJECT');
export const UPDATE_USER_INFO = namespace('UPDATE_USER_INFO');
export const REPLACE_VALUES = namespace('REPLACE_VALUES');
export const UPDATE_ENGINE_ERROR = namespace('UPDATE_ENGINE_ERROR');
export const REINITIALIZE_ENGINE_STATE= namespace('REINITIALIZE_ENGINE_STATE');
export const UPDATE_DYNAMIC_SECTIONS = namespace('UPDATE_DYNAMIC_SECTIONS');
export const UPDATE_LOAD_COMPLETED = namespace('UPDATE_LOAD_COMPLETED');
export const UPDATE_IS_DEBUG_ENABLED = namespace('UPDATE_IS_DEBUG_ENABLED');
export const UPDATE_USER_ACTIVITY = namespace('UPDATE_USER_ACTIVITY');